# Generated by Django 2.1.5 on 2019-01-10 14:33

import Users.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('matchID', models.AutoField(primary_key=True, serialize=False)),
                ('entryFree', models.IntegerField()),
                ('winPrize', models.IntegerField()),
                ('perKill', models.IntegerField()),
                ('size', models.IntegerField()),
                ('matchMap', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=25)),
                ('matchType', models.CharField(max_length=25)),
                ('matchVersion', models.CharField(max_length=25)),
                ('timedata', models.DateTimeField()),
                ('totalPeopleJoined', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaytmHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(default=Users.models.increment, editable=False, max_length=30, unique=True)),
                ('txndeta', models.DateTimeField(auto_now_add=True, null=True)),
                ('transactionid', models.CharField(editable=False, max_length=120, null=True)),
                ('txnamount', models.FloatField(default=0.0)),
                ('status', models.CharField(default='pending', editable=False, max_length=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerJoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubgusername', models.CharField(max_length=25, null=True)),
                ('matchKill', models.IntegerField(default=0)),
                ('moneyEarn', models.IntegerField(default=0)),
                ('update', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PubgUser',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(blank=True, max_length=25, null=True)),
                ('lastName', models.CharField(blank=True, max_length=25, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('myKills', models.IntegerField(default=0)),
                ('matchesPlayed', models.IntegerField(default=0)),
                ('amountWon', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='RequestMoney',
            fields=[
                ('RequestID', models.AutoField(primary_key=True, serialize=False)),
                ('money', models.FloatField(default=0)),
                ('phone', models.CharField(max_length=10)),
                ('paid', models.CharField(default='no', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SentMoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('status', models.CharField(default='failed', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('TransID', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(default='failed', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
                ('updateinfo', models.CharField(max_length=225)),
                ('updateurl', models.CharField(max_length=50)),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('walletID', models.AutoField(primary_key=True, serialize=False)),
                ('balance', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='playerjoin',
            name='joinID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Users.Transactions'),
        ),
        migrations.AddField(
            model_name='playerjoin',
            name='matchID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Users.Event'),
        ),
        migrations.AddField(
            model_name='playerjoin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
