# Generated by Django 2.1.5 on 2019-01-10 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20190110_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerjoin',
            name='joinID',
        ),
    ]
