# Generated by Django 2.1.5 on 2019-01-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_auto_20190111_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerjoin',
            name='type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
