# Generated by Django 2.1.5 on 2019-01-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_playerjoin_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
