# Generated by Django 2.1.5 on 2019-01-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_roompass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roompass',
            name='passID',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='roompass',
            name='roomID',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
