# Generated by Django 2.1.5 on 2019-01-12 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_auto_20190112_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='passID',
        ),
        migrations.RemoveField(
            model_name='event',
            name='roomID',
        ),
    ]
