# Generated by Django 2.1.5 on 2019-01-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_auto_20190112_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='img',
            field=models.URLField(null=True),
        ),
    ]
