# Generated by Django 2.1.5 on 2019-01-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_event_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
