# Generated by Django 2.1.5 on 2019-01-12 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0016_auto_20190113_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roompass',
            name='matchID',
        ),
        migrations.DeleteModel(
            name='RoomPass',
        ),
    ]
