# Generated by Django 2.1.5 on 2019-01-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0017_auto_20190113_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='img',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='passID',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='roomID',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
