# Generated by Django 2.1.5 on 2019-01-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0018_auto_20190113_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='img',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='passID',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='roomID',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
