# Generated by Django 2.1.5 on 2019-01-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0019_auto_20190113_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmoney',
            name='paid',
            field=models.BooleanField(default=False, max_length=10),
        ),
    ]
